name: CI

on:
  push:
    branches: [test-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 12.18.0

      - name: Copy code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{  secrets.SSH_KEY }}
          source: "./teste"
          target: "~/teste/"

      - name: Install dependencies on server and restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{  secrets.SSH_KEY }}
          script: |
            cd /home/deploy/teste
